### DISCUSSION TITLE
Issue with the multi-values in upstream_*_time

### DISCUSSION THREAD

**Discussion by Nereis** [martin-helmich/prometheus-nginxlog-exporter#321] [Q&A]
Hi,

According to issue #217, nginx log exporter does support the multiple values for the upstream_response_time and I assume for upstream_connect_time and upstream_header_time too. 

I'm still facing a parsing error when nginx provides multiples values there. It works fine with other entry. 

```
Apr 05 13:50:47 jira1 prometheus-nginxlog-exporter[64094]: error while parsing line 
'[05/Apr/2023:13:50:47 +0200] client=11.11.11.11 remote_user="-" request="GET /url.png HTTP/1.1" request_length=501 status=200 body_bytes_sent=3147 referer="-" user_agent="Some navigator" x_forwarded="1.11.11.11, 1.11.11.11" request_time=0.010 upstream_response_time=0.004, 0.008 upstream_connect_time=0.004, 0.000 upstream_header_time=0.004, 0.004 subnet=11.11.11.11'
: text log parsing err: access log line 
'[05/Apr/2023:13:50:47 +0200] client=11.11.11.11 remote_user="-" request="GET /url.png HTTP/1.1" request_length=501 status=200 body_bytes_sent=3147 referer="-" user_agent="Some navigator" x_forwarded="11.11.11.11, 1.11.11.11" request_time=0.010 upstream_response_time=0.004, 0.008 upstream_connect_time=0.004, 0.000 upstream_header_time=0.004, 0.004 subnet=11.11.11.11' 
does not match given format 
'^\[(?P<time_local>[^]]*)\] client=(?P<remote_addr>[^ ]*) remote_user="(?P<remote_user>[^"]*)" request="(?P<request>[^"]*)" request_length=(?P<request_length>[^ ]*) status=(?P<status>[^ ]*) body_bytes_sent=(?P<body_bytes_sent>[^ ]*) referer="(?P<http_referer>[^"]*)" user_agent="(?P<http_user_agent>[^"]*)" x_forwarded="(?P<http_x_forwarded_for>[^"]*)" request_time=(?P<request_time>[^ ]*) upstream_response_time=(?P<upstream_response_time>[^ ]*) upstream_connect_time=(?P<upstream_connect_time>[^ ]*) upstream_header_time=(?P<upstream_header_time>[^ ]*)'
```

Nginx log format
```
map $remote_addr $remote_addr_subnet {
    ~(?P<ip>\d+\.\d+\.\d+)\.    $ip.0;
    ~(?P<ip>[^:]+:[^:]+):       $ip::;
    default                     unknown;
}

log_format custom '[$time_local] client=$remote_addr remote_user=\"$remote_user\" request=\"$request\" request_length=$request_length status=$status body_bytes_sent=$body_bytes_sent referer=\"$http_referer\" user_agent=\"$http_user_agent\" x_forwarded=\"$http_x_forwarded_for\" request_time=$request_time upstream_response_time=$upstream_response_time upstream_connect_time=$upstream_connect_time upstream_header_time=$upstream_header_time subnet=$remote_addr_subnet';

```

Nginx log exporter config
```
listen:
  port: 4040
  address: "127.0.0.1"
  metrics_endpoint: "/metrics"

consul:
  enable: false

namespaces:
  - name: nginx
    format: "[$time_local] client=$remote_addr remote_user=\"$remote_user\" request=\"$request\" request_length=$request_length status=$status body_bytes_sent=$body_bytes_sent referer=\"$http_referer\" user_agent=\"$http_user_agent\" x_forwarded=\"$http_x_forwarded_for\" request_time=$request_time upstream_response_time=$upstream_response_time upstream_connect_time=$upstream_connect_time upstream_header_time=$upstream_header_time"

    source:
      files:
        - /var/log/nginx/toto.log
    histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
```

According to the exception, the matching issue is there

```
upstream_response_time=(?P<upstream_response_time>[^ ]*)
upstream_response_time=0.004, 0.008
```

which extracts `0.004,` instead of `0.004, 0.008`

I'm using v1.10.0. 

I'm pretty sure I read something about it while ago and it was related to the parse format but I can't get my hands on it again. 

Note: the last field subnet doesn't look to have any impact on it. It's something we activate on demand since it generates quite a lot of metrics. 

Any idea ? 

Thank you in advance.
