### DISCUSSION TITLE
Can't relable upstream_addr

### DISCUSSION THREAD

**Discussion by Danbasik230** [martin-helmich/prometheus-nginxlog-exporter#405] [Q&A]
I want to add upstream_addr in configuration, want to build new metric. When I try to do it, I don't have an issue, but it doesn't work, any of variants what I have in documentation. What I should to do?

That's variant not working
```
  - name: webapi
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" <msec=$msec|connection=$connection|connection_requests=$connection_requests|millis=$request_time|upstream_addr=$upstream_addr|upstream_resp_time=$upstream_response_time|upstream_status=$upstream_status|nodeid=$upstream_http_x_nodeid>"
    source:
      files:
        - /var/log/nginx/webapi.access.log
        - /var/log/nginx/webapi.access.log
    labels:
      service: "webapi"
      instance: "server"
    relabel_configs:
      - source_labels: ["upstream_addr"]
        target_label: "upstream_addr"

```

webapi_http_response_count_total{instance="server",method="GET",service="webapi",status="302"} 9
webapi_http_response_count_total{instance="server",method="GET",service="webapi",status="400"} 1076
..... etc

Also tried to do smth like that, didn't work
```
    labels:
      service: "webapi"
      instance: "server"
      upstream_addr: "$upstream_addr"
```

webapi_http_upstream_time_seconds_hist_bucket{instance="server",method="GET",service="webapi",status="405", upstream_addr= "",le="0.005"} 1
webapi_http_upstream_time_seconds_hist_bucket{instance="server",method="GET",service="webapi",status="405", upstream_addr= "",le="0.01"} 1

Example of my nginx log

```
1.1.1.1 - - [27/Nov/2024:07:19:56 +0300] "GET /api/1.0/partner/5bdb173a97a528242011b613/unsubscribe?apiKey=5bdb173a97a528242011b614&email=test HTTP/2.0" 200 0 "-" "Symfony HttpClient (Curl)" "-" <msec=1732681196.742|connection=38894584|connection_requests=1|millis=0.005|upstream_addr=1.1.1.1:80|upstream_resp_time=0.004|upstream_status=200|nodeid=->
1.1.1.1 - - [27/Nov/2024:07:20:49 +0300] "GET /api/1.0/partner/5c04ef4397a5281c7c113d50/unsubscribe?apiKey=5c04ef4397a5281c7c113d51&email=test HTTP/2.0" 200 0 "-" "Symfony HttpClient (Curl)" "-" <msec=1732681249.718|connection=38896674|connection_requests=1|millis=0.003|upstream_addr=1.1.1.1:80|upstream_resp_time=0.004|upstream_status=200|nodeid=->
1.1.1.1 - - [27/Nov/2024:07:24:40 +0300] "GET /api/1.0/partner/5bdb173a97a528242011b613/unsubscribe?apiKey=5bdb173a97a528242011b614&email=test HTTP/2.0" 200 0 "-" "Symfony HttpClient (Curl)" "-" <msec=1732681480.396|connection=38907758|connection_requests=1|millis=0.005|upstream_addr=1.1.1.1:80|upstream_resp_time=0.008|upstream_status=200|nodeid=->
1.1.1.1 - - [27/Nov/2024:07:25:26 +0300] "GET /api/1.0/partner/5c04f01e97a5252b48ef35da/unsubscribe?apiKey=5c04f01e97a5252b48ef35db&email=test HTTP/2.0" 200 0 "-" "Symfony HttpClient (Curl)" "-" <msec=1732681526.796|connection=38909758|connection_requests=1|millis=0.004|upstream_addr=1.1.1.1:80|upstream_resp_time=0.004|upstream_status=200|nodeid=->
```
