### ISSUE TITLE
Filter access.log with hostname

### ISSUE THREAD

**Issue by awronski** [martin-helmich/prometheus-nginxlog-exporter#106]
I have one access.log for all virtual hosts on the machine. With a log format like this:

    log_format main '$remote_addr - $remote_user [$time_local] '
            '"$host" "$request" $status $body_bytes_sent '
            '$request_time $upstream_response_time '
            '"$http_referer" "$http_user_agent"';
Is there any way I can filter metrics just for one host?
Or can I group metrics by host name?

Thanks!

**Comment by martin-helmich** [comment]
I would suggest doing filtering & aggregation on the query side (using PromQL), not while scraping (e.g. `app_http_response_count_total{host="example.com"}` for filtering and `sum(app_http_response_count_total) by (host)` for aggregation). You can add the host as label to the exported time series by adding a [`relabel` config](https://github.com/martin-helmich/prometheus-nginxlog-exporter#dynamic-re-labeling).

**Comment by awronski** [comment]
@martin-helmich Thanks, it's working!

Solution if someone is looking for this to:
```yaml
namespaces:
  - name: nginx
    format: "$remote_addr - $remote_user [$time_local] \"$host\" \"$request\" $status $body_bytes_sent $request_time $upstream_response_time \"$http_referer\" \"$http_user_agent\""
    source:
      files:
        - /mnt/nginxlogs/access.log
    labels:
      app: "app"
      environment: "production"
    relabel_configs:
       - target_label: host
         from: "host"
         whitelist: [ "host1.com", "api.host.com" ]
```
