### ISSUE TITLE
Allow Glob for files

### ISSUE THREAD

**Issue by Gui13** [martin-helmich/prometheus-nginxlog-exporter#176]
**Is your feature request related to a problem? Please describe.**

My nginx issues many logfiles, one per domain name, in the following simplified hierearchy:

`/var/log/nginx/client1/${domain_name}_access.log`

Where `domain_name` has many values and changes regularly (we have a dynamic inventory of domain names and the configuration is added automatically in nginx).

I have to manually add all files to the `files = [ x, y, z ]` for each of my clients, eg: 

```yaml

namespaces:
  - name: client&
    format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time $upstream_response_time $upstream_connect_time'
    source:
      files:
        - /var/log/nginx/client1/xxx_access.log
        - /var/log/nginx/client1/yyy_access.log
        - a dozen more
```

**Describe the solution you'd like**

I'd like the files to be "globable" like this:

```yaml

namespaces:
  - name: client&
    format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time $upstream_response_time $upstream_connect_time'
    source:
      files:
        - /var/log/nginx/client1/(.*)_access.log  # automatically picks up all files matching this pattern at boot and on SIGHUP
```

**Describe alternatives you've considered**

I could spin up some kind of patching to the current configuration so that when an new nginx configuration (and logfile) is added, I can add it to the corresponding namespace, but I am not quite sure how much effort it would entice, rather than implement a basic globing in nginxlog-exporter for that feature.

We run bare-metal, not kubernetes. In a K8S environment, I'd have considered adding CRDs maybe to symbolize a namespace and dynamically poplate the configuration with that.

**Additional context**
