### ISSUE TITLE
cannot set `only_counter` for `status`, daemon panics

### ISSUE THREAD

**Issue by vthriller** [martin-helmich/prometheus-nginxlog-exporter#216]
**Issue type**: Bug report  

**What happened**:

```
panic: inconsistent label cardinality: expected 3 label values but got 2 in []string{"rpc", "POST"}

goroutine 65 [running]:
github.com/prometheus/client_golang/prometheus.(*CounterVec).WithLabelValues(0xc000182078, 0xc000390030, 0x2, 0x3, 0xb63401, 0xc000354060)
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/counter.go:248 +0xdf
main.processSource(0xc0001b00d8, 0x4, 0x0, 0x0, 0x0, 0xc0001a43b0, 0x0, 0x0, 0xc0001d60c0, 0xc, ...)
        /home/runner/work/prometheus-nginxlog-exporter/prometheus-nginxlog-exporter/main.go:408 +0x6ed
created by main.processNamespace
        /home/runner/work/prometheus-nginxlog-exporter/prometheus-nginxlog-exporter/main.go:353 +0x232
```

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
    relabel_configs:
    - target_label: status
      #from: status # panics both with and without this option
      only_counter: true
```

**Environment**:
- Exporter version: 1.9.0
- OS (e.g. from /etc/os-release): any
