### ISSUE TITLE
<namespace>_parse_errors_total" counter and exception for united namespaces (reopen)

### ISSUE THREAD

**Issue by xzert** [martin-helmich/prometheus-nginxlog-exporter#244]
**Is your feature request related to a problem? Please describe.**
When one of namespaces have errors by some reason (wrong format, not accessible logfile, etc) exporter drop exception like "parse_errors_total was collected previous" (not literally)
(reopen for #212 )

**Describe the solution you'd like**
Do conjuction of parse_errors_total metrics in united namespace and increase metric gauge

**Describe alternatives you've considered**
Maybe add namespace_label for parse_errors_total metric for possible separate broken namespace configs

Sample:
```
listen:
  port: 9040
  address: 0.0.0.0
  metrics_endpoint: "/metrics"

namespaces:
  - name: 'domain'
    format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" req_t=$request_time up_con_t="$upstream_connect_time" up_head_t="$upstream_header_time" up_resp_t="$upstream_response_time"'
    source:
      files:
       - '/var/log/nginx/domain.access.log'
    metrics_override:
      prefix: ""
      namespace_label: "domain"
    labels:
      environment: "production"
    histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
  - name: 'domain_api'
    format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" req_t=$request_time up_con_t="$upstream_connect_time" up_head_t="$upstream_header_time" up_resp_t="$upstream_response_time"'
    source:
      files:
       - '/var/log/nginx/domain-api.local.access.log'
    metrics_override:
      prefix: ""
      namespace_label: "domain-api.local"
    labels:
      environment: "production"
    histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]

```
Output:
```
An error has occurred while serving metrics:

collected metric "parse_errors_total" { counter:<value:0 > } was collected before with the same name and label values
```

**Comment by martin-helmich** [comment]
Apologies for the late response. This should not have gotten stale. I'll investigate shortly.

**Comment by martin-helmich** [comment]
I've had a look at your configuration file and found a few issues that in combination will most likely be causing this effect.

1. The `namespace_label` property needs to be defined on the root level of each namespace, and *not* under `metrics_override`. Either a `namespace_label` or a `metrics_override.prefix` needs to be set, otherwise the exporter will publish multiple time series with the exact same names and labels (which leads to the exact _"collected metric blabla was collected before with the same name and label values"_ error).

   So, instead of...

   ```yaml
       metrics_override:
         prefix: ""
         namespace_label: "domain"
   ```

   please try

   ```yaml
       namespace_label: "domain"
       metrics_override:
         prefix: ""
   ```

2. Also, the `namespace_label` is supposed to contain the _name_ of the label in which the namespace name (so, just `name`) should be saved. In your case, the exporter will try to use `domain-api.local` as a label _name_, which is not a valid label name for Prometheus. Best just use something like `"namespace"`, `"vhost"` or `"app"` as label name.

Hope that helps.
