### ISSUE TITLE
Constantly leaking memory

### ISSUE THREAD

**Issue by rerime** [martin-helmich/prometheus-nginxlog-exporter#264]
**Describe the bug**
Constantly leaking memory

**Expected behavior**
Memory not leak

**Configuration file** (remove section, if not applicable):

```
listen:
  port: 4040
  address: "0.0.0.0"
  metrics_endpoint: "/metrics"

namespaces:
  - name: nginx
    format: '[$time_local] $remote_addr $request_method "$host" "$request_uri" $status $request_length $bytes_sent "$http_referer" "$http_user_agent" "$upstream_addr" $upstream_status rt="$request_time" uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"'
    source:
      files:
        - /mnt/nginxlogs/access.log
    relabel_configs:
    - target_label: host
      from: host
    - target_label: request
      from: request_uri
    - target_label: method
      from: request_method
    labels:
    histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]
```

**Environment**:

- Exporter version: 1.9.2
- OS (e.g. from /etc/os-release): RHEL 8.5
