### ISSUE TITLE
Dynamic namespace name

### ISSUE THREAD

**Issue by strangeman** [martin-helmich/prometheus-nginxlog-exporter#46]
**Support request**:

**What happened**:
We have the following filenames convention for the log files: `appname_[access|error].log`. Is there a way to create a config, which takes a namespace and application name dynamically, via regexp?

Something like:

```
namespaces:
  - name: $1
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
    source_files:
      - /var/log/nginx/(\w+)_access.log
    labels:
      app: "$1"
      environment: "production"
      foo: "bar"
```
