### ISSUE TITLE
Can we include the access url in the export?

### ISSUE THREAD

**Issue by Adel-Magebinary** [martin-helmich/prometheus-nginxlog-exporter#53]
**Issue type**:
> Feature request  

**What you expected to happen**:

Wanting to report a table in garafana to show lists of URL that have errors.

**Comment by martin-helmich** [comment]
You can use a relabeling configuration:

```yaml
namespaces:
- name: app1
  relabel_configs:
  - target_label: request_uri
    from: request
    split: 2
    matches:
    - regexp: "^/users/[0-9]+"
      replacement: "/users/:id"
```

To simply pass through all URLs (slightly hacky, but should work):

```yaml
namespaces:
- name: app1
  relabel_configs:
  - target_label: request_uri
    from: request
    split: 2
    matches:
    - regexp: "^(.*)$"
      replacement: "$1"
```

Keep in mind that using unbound label sets (by using simply the URL as label value) might create a high series churn in Prometheus. Use at your own risk.
