### ISSUE TITLE
Check Configuration

### ISSUE THREAD

**Issue by dioobr** [martin-helmich/prometheus-nginxlog-exporter#57]
**Issue type**:
> Support request

**What happened**:
I did the installation, but it looks like it's missing some metrics. I want to make sure I'm not doing anything wrong.

**What you expected to happen**:
In your blog, you mention some metrics (https://www.martin-helmich.de/en/blog/monitoring-nginx.html), like app_http_response_time_seconds_sum, app_http_response_time_seconds_count, app_http_response_time_seconds_count, app_http_response_size_bytes, etc, but in prometheus (my_server: 9090), only the following metrics appear to me:
- app_http_response_count_total
- app_http_response_size_bytes
- http_request_duration_microseconds
- http_request_duration_microseconds_count
- http_request_duration_microseconds_sum
- http_request_size_bytes
- http_request_size_bytes_count
- http_request_size_bytes_sum
- http_requests_total
- http_response_size_bytes
- http_response_size_bytes_count
- http_response_size_bytes_sum

**Configuration file** (remove section, if not applicable):
```
listen {
  port = 4040
  address = "localhost"
}

namespace "app" {
  format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\""
  source_files = [
     "/var/log/ispconfig/httpd/example.com/access.log"
  ]
}
```
prometheus.yml
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'nginxlog-exporter'
    static_configs:
      - targets: ['localhost:4040']
```

**Environment**:
- Exporter version: v1.2.1
- OS (e.g. from /etc/os-release): CentOS
- Others: Prometheus 2.6.0
