### ISSUE TITLE
Prometheus -nginxlog-exporter throws errors

### ISSUE THREAD

**Issue by xichengliudui** [martin-helmich/prometheus-nginxlog-exporter#79]
**Issue type**:

> Support request

**What happened**:
execute: `./prometheus-nginxlog-exporter -config-file ./exporter-config.yml`
```
loading configuration file ./exporter-config.yml
using configuration {Listen:{Port:3309 Address:10.20.11.117} Consul:{Enable:false Address: Datacenter: Scheme: Token: Service:{ID: Name: Tags:[]}} Namespaces:[{Name:nginx-log SourceFiles:[/opt/nginx/log/access.log] Format:$proxy_protocol_addr - $remote_addr - $http_host - [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $upstream_response_time Labels:map[] RelabelConfigs:[] HistogramBuckets:[] OrderedLabelNames:[] OrderedLabelValues:[]}] EnableExperimentalFeatures:false EnableExperimentalFeaturesOld:false}
starting listener for namespace nginx-log
running HTTP server on address 10.20.11.117:3309
panic: descriptor Desc{fqName: "nginx-log_http_response_count_total", help: "Amount of processed HTTP requests", constLabels: {}, variableLabels: [method status]} is invalid: "nginx-log_http_response_count_total" is not a valid metric name

goroutine 35 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000024640, 0xc00005d250, 0x1, 0x1)
	/Golang/pkg/mod/github.com/prometheus/client_golang@v0.0.0-20160916180340-5636dc67ae77/prometheus/registry.go:404 +0xad
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/Golang/pkg/mod/github.com/prometheus/client_golang@v0.0.0-20160916180340-5636dc67ae77/prometheus/registry.go:152
main.(*Metrics).Init(0xc000024ac0, 0xc0000bdf40)
	/Golang/prometheus-nginxlog-exporter/main.go:108 +0x9a2
main.processNamespace(0xc00015e0a0, 0x9, 0xc000150220, 0x1, 0x1, 0xc00017a000, 0x9f, 0x0, 0x0, 0x0, ...)
	/Golang/prometheus-nginxlog-exporter/main.go:234 +0x90
created by main.main
	/Golang/prometheus-nginxlog-exporter/main.go:181 +0x904
```

**What you expected to happen**:

**running**

**How to reproduce it (as minimally and precisely as possible)**:

**./prometheus-nginxlog-exporter -config-file ./exporter-config.yml**

**Other important information**:

**Use the nginx default configuration**

**Configuration file** (remove section, if not applicable):

```
listen:
  port: 3309
  address: "10.20.11.117"
namespaces:
   - name: nginx-log
     format: "$proxy_protocol_addr - $remote_addr - $http_host - [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $upstream_response_time"
     # format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
     source_files:
       - /opt/nginx/log/access.log
```

```
# Please post the output of the exporter's /metrics endpoint, if applicable
```

**Example log file** (remove section, if not applicable):

nginx log
```
10.20.50.177 - - [28/Aug/2019:10:39:56 +0000] "GET /api/portal/app/3fffc15d-cc2a-4547-b166-40f5421ca5a9 HTTP/1.1" 200 1962 "http://10.20.11.117:8801/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:42:48 +0000] "GET /api/infos?page=0&rows=10 HTTP/1.1" 200 2268 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:43:42 +0000] "PUT /api/info HTTP/1.1" 200 218 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:43:42 +0000] "GET /api/infos?page=0&rows=10 HTTP/1.1" 200 2277 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:44:26 +0000] "GET /api/infos?page=0&rows=10 HTTP/1.1" 200 2277 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:44:54 +0000] "GET /api/routes?page=0&rows=10 HTTP/1.1" 200 3165 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:44:56 +0000] "GET /api/infos?page=0&rows=10 HTTP/1.1" 200 2277 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:01 +0000] "GET /api/routes?page=0&rows=10 HTTP/1.1" 200 3165 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:04 +0000] "GET /api/infos?page=0&rows=10 HTTP/1.1" 200 2277 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:06 +0000] "GET /api/routes?page=0&rows=10 HTTP/1.1" 200 3165 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:16 +0000] "PUT /api/route/7118145c-6bc9-43e1-854a-6e5330b86e40/maintain HTTP/1.1" 200 743 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:16 +0000] "GET /api/routes?page=0&rows=10 HTTP/1.1" 200 3200 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:19 +0000] "DELETE /api/route/7118145c-6bc9-43e1-854a-6e5330b86e40 HTTP/1.1" 200 162 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:22 +0000] "GET /api/infos?page=0&rows=10 HTTP/1.1" 200 2277 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:27 +0000] "DELETE /api/info/acf827c3-a954-4932-8db3-13da4e62bd6a HTTP/1.1" 200 218 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:27 +0000] "GET /api/infos?page=0&rows=10 HTTP/1.1" 200 382 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:29 +0000] "GET /api/routes?page=0&rows=10 HTTP/1.1" 200 3200 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:33 +0000] "GET /api/serviceManage/findServiceName?page=0&rows=10 HTTP/1.1" 200 2384 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:34 +0000] "GET /api/routes?page=0&rows=10 HTTP/1.1" 200 3200 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.177 - - [28/Aug/2019:10:45:35 +0000] "GET /api/serviceManage/findServiceName?page=0&rows=10 HTTP/1.1" 200 2384 "http://10.20.11.117:8800/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" "-"
10.20.50.149 - - [29/Aug/2019:03:02:30 +0000] "GET / HTTP/1.1" 200 578 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
10.20.50.149 - - [29/Aug/2019:03:02:30 +0000] "GET /static/js/manifest.cf3d4d515cbe423cd60d.js HTTP/1.1" 200 1485 "http://10.20.11.117:8801/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
10.20.50.149 - - [29/Aug/2019:03:02:30 +0000] "GET /static/css/app.e1b767eac39024c24da2635492bec93d.css HTTP/1.1" 200 267669 "http://10.20.11.117:8801/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
```

**Environment**:
- Exporter version:
- OS (e.g. from /etc/os-release): centos7
- Others:

**Comment by xichengliudui** [comment]
error：`panic: descriptor Desc{fqName: "nginx-log_http_response_count_total", help: "Amount of processed HTTP requests", constLabels: {}, variableLabels: [method status]} is invalid: "nginx-log_http_response_count_total" is not a valid metric name`

**Comment by xichengliudui** [comment]
I think this is a bug because I succeeded after modifying the configuration.
```
listen:
  port: 3309
  address: "10.20.11.117"
namespaces:
   - name: loginfo
     format: "$proxy_protocol_addr - $remote_addr - $http_host - [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" $upstream_response_time"
     # format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
     source_files:
       - /opt/nginx/log/access.log
```
