### ISSUE TITLE
Docker container failing to accept connections

### ISSUE THREAD

**Issue by Purushotham233** [martin-helmich/prometheus-nginxlog-exporter#86]
**Issue type**:
> Bug report  

**What happened**:
Running the docker container with the below command:
docker run --name nginx-exporter -d -p 4040:4040 -v /home/purushotham:/var/log/nginx -v /home/purushotham/log_exporter.yaml:/etc/log_exporter.yaml quay.io/martinhelmich/prometheus-nginxlog-exporter -config-file /etc/log_exporter.yaml

Docker logs says below but when accessing localhost:4040/metrics getting the connection reset by peer error:
```
loading configuration file /etc/log_exporter.yaml
using configuration {{%!s(int=4040) localhost} {%!s(bool=false)     {  []}} [{dr_nginx [/var/log/nginx/access.log] $remote_addr "$request" map[] [] [] []}] %!s(bool=false)}
starting listener for namespace dr_nginx
running HTTP server on address localhost:4040
```

**What you expected to happen**:
Able to access the /metrics endpoint.

**How to reproduce it (as minimally and precisely as possible)**:

**Other important information**:

**Configuration file** (remove section, if not applicable):

```yaml
listen:
  port: 4040
  address: "localhost"

namespaces:
  - name: dr_nginx
    format: "$remote_addr \"$request\""
    source_files:
      - /var/log/nginx/access.log
```

**Exporter output** (remove section, if not applicable):

```
Not able to access the endpoint /metrics.
```

**Example log file** (remove section, if not applicable):

```
10.32.18.146 "HEAD /v2/ HTTP/1.1"
```

**Environment**:
- Exporter version: latest, quay.io/martinhelmich/prometheus-nginxlog-exporter@sha256:a399a93dd30c54409d398d49ca31d81e5822ee656fe0b7c8b5c47a5d02eba8e6
